#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 18 12:18:22 2022

@author: baye
"""

sql1 = "SELECT * FROM AGENCE"


sql2 = "SELECT Id_USER, nom_USER FROM USERS WHERE id_PROFIL_PROFIL = 3 ORDER BY nom_USER"


sql3 = "SELECT Id_USER, nom_USER, adresse_AGENCE FROM USERS JOIN AGENCE ON id_USER = numero_AGENCE WHERE id_PROFIL_PROFIL = 1"


sql4 = "SELECT numero, solde_COMPTE_TRANSACTION, adresse_AGENCE FROM COMPTE_TRANSACTION as t JOIN AGENCE as a ON t.numero = a.numero_AGENCE WHERE adresse_AGENCE = '5 Nova Road' ORDER BY solde_COMPTE_TRANSACTION"


sql5 = "SELECT montant_TRANSACTION AS Somme_Montant FROM TRANSACTIONS AS t JOIN USERS AS u ON t.num_TRANSACTION = u.id_USER WHERE u.nom_USER = 'Slott' AND u.id_PROFIL_PROFIL = 1 ORDER BY montant_TRANSACTION ASC"


sql6 = """ SELECT nom_USER FROM USERS AS U JOIN AGENCE AS A ON U.id_USER = A.numero_AGENCE WHERE adresse_AGENCE = '5 Nova Road' """


sql7 = "SELECT adresse_AGENCE, COUNT(numero_COMPTE_TRANSACTION) AS Nombre_de_comptes FROM ASSOCIER AS ASS JOIN AGENCE AS A ON ASS.id_USER_USER = A.numero_AGENCE GROUP BY adresse_AGENCE"


sql8 = """ SELECT date_debut, numero_COMPTE_TRANSACTION FROM ASSOCIER AS A JOIN USERS AS U ON A.id_USER_USER = U.id_USER WHERE U.nom_USER = 'Slott' AND date_debut BETWEEN '2021-04-30' AND '2021-06-01' """


sql9 = """ SELECT nom_USER FROM USERS AS U JOIN COMPTE_TRANSACTION AS C ON U.id_USER = C.numero WHERE C.numero = 1 AND C.dateCreattion_COMPTE_TRANSACTION BETWEEN '2020-12-31' AND '2022-01-01' """


sql10 = "SELECT nom_USER, montant_TRANSACTION FROM TRANSACTIONS AS T JOIN USERS AS U ON T.id_USER_USER = U.id_USER WHERE T.numero_AGENCE_AGENCE = 1"

sql11 = "SELECT  numero_COMPTE_TRANSACTION FROM ASSOCIER AS A JOIN USERS AS U ON U.id_USER = A.id_USER_USER WHERE U.numero_AGENCE_AGENCE = 1 AND A.date_debut BETWEEN '2020-12-31' AND '2021-04-01' GROUP BY A.numero_COMPTE_TRANSACTION  ORDER BY A.numero_COMPTE_TRANSACTION "


sql12 = "SELECT num_DEPOTouRETRAIT, montant_TRANSACTION FROM TRANSACTIONS WHERE numero_AGENCE_AGENCE = 8 ORDER BY montant_TRANSACTION ASC"


sql13 = """ SELECT nom_CLIENT, montant_TRANSACTION, frais_TRANSACTION  FROM TRANSACTIONS AS T JOIN CLIENT AS C WHERE T.numero_AGENCE_AGENCE  = 8 AND nom_CLIENT = 'Rentenbeck' """


sql14 = "SELECT date_TRANSACTION, montant_TRANSACTION*0.1 as Part_Agence, montant_TRANSACTION*0.4 as Part_Etat, etat_AGENCE  FROM TRANSACTIONS AS T JOIN AGENCE AS A ON A.numero_AGENCE = T.num_TRANSACTION WHERE A.numero_AGENCE = 8 GROUP BY T.date_TRANSACTION"


sql15 = "SELECT date_TRANSACTION, montant_TRANSACTION*0.1 as Part_Agence, montant_TRANSACTION*0.4 as Part_Etat, etat_AGENCE  FROM TRANSACTIONS AS T JOIN AGENCE AS A ON A.numero_AGENCE = T.num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '1980-12-31' AND '2012-01-01'GROUP BY A.numero_AGENCE"


sql16 = "SELECT numero_AGENCE_AGENCE,adresse_AGENCE, num_DEPOTouRETRAIT FROM TRANSACTIONS AS T JOIN AGENCE AS A ON numero_AGENCE=num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '2021-05-31' AND '2021-07-01' AND T.id_TYPE_TYPE = 1 OR T.id_TYPE_TYPE = 2 AND T.num_DEPOTouRETRAIT = (SELECT MAX(num_DEPOTouRETRAIT) FROM TRANSACTIONS)"


sql17 = "SELECT numero_AGENCE_AGENCE,adresse_AGENCE, num_DEPOTouRETRAIT FROM TRANSACTIONS AS T JOIN AGENCE AS A ON numero_AGENCE=num_TRANSACTION WHERE T.date_TRANSACTION = '2021-08-10' AND T.id_TYPE_TYPE = 1 OR T.id_TYPE_TYPE = 2 AND T.num_DEPOTouRETRAIT = (SELECT MIN(num_DEPOTouRETRAIT) FROM TRANSACTIONS)"

sql18 = "SELECT numero_AGENCE_AGENCE,adresse_AGENCE, num_DEPOTouRETRAIT FROM TRANSACTIONS AS T JOIN AGENCE AS A ON numero_AGENCE=num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '2021-04-31' AND '2021-06-01' AND T.id_TYPE_TYPE = 2 AND T.num_DEPOTouRETRAIT = (SELECT MAX(num_DEPOTouRETRAIT) FROM TRANSACTIONS)"


sql19 = "SELECT numero_AGENCE_AGENCE,adresse_AGENCE, num_DEPOTouRETRAIT FROM TRANSACTIONS AS T JOIN AGENCE AS A ON numero_AGENCE=num_TRANSACTION WHERE T.date_TRANSACTION = '2018-07-07' AND T.id_TYPE_TYPE = 1 AND T.num_DEPOTouRETRAIT = 0"


sql20 = "SELECT nom_CLIENT, date_TRANSACTION AS Periode FROM CLIENT AS C JOIN TRANSACTIONS AS T ON C.nci_CLIENT = T.num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '2021-04-31' AND '2021-06-01' AND T.numero_AGENCE_AGENCE = 1"


sql21 = "SELECT nom_CLIENT, montant_TRANSACTION FROM CLIENT AS C JOIN TRANSACTIONS AS T ON C.nci_CLIENT = T.num_TRANSACTION WHERE date_TRANSACTION BETWEEN '2021-04-31' AND '2021-06-01' AND T.montant_TRANSACTION = (SELECT MIN(montant_TRANSACTION) FROM TRANSACTIONS)"


sql22 = "SELECT nom_CLIENT, montant_TRANSACTION FROM CLIENT AS C JOIN TRANSACTIONS AS T ON C.nci_CLIENT = T.num_TRANSACTION WHERE date_TRANSACTION BETWEEN '2021-04-31' AND '2021-06-01' AND T.montant_TRANSACTION = (SELECT MAX(montant_TRANSACTION) FROM TRANSACTIONS)"


sql23 = """ SELECT adresse_AGENCE, MAX(num_DEPOTouRETRAIT) AS Nombre_Transactions FROM AGENCE AS A JOIN TRANSACTIONS AS T ON A.numero_AGENCE = T.num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '2000-12-31' AND '2022-01-01' GROUP BY A.adresse_AGENCE  LIMIT 5 """



sql24 = "SELECT adresse_AGENCE, SUM(frais_TRANSACTION) AS Montant_gagnes FROM AGENCE AS A JOIN TRANSACTIONS AS T ON A.numero_AGENCE = T.num_TRANSACTION WHERE T.date_TRANSACTION BETWEEN '2000-12-31' AND '2022-01-01' AND T.frais_TRANSACTION = (SELECT MIN(T.frais_TRANSACTION) FROM TRANSACTIONS) GROUP BY A.adresse_AGENCE  LIMIT 5"


sql25 = "SELECT nom_USER, num_DEPOTouRETRAIT FROM TRANSACTIONS AS T JOIN USERS AS U ON U.id_USER = T.num_TRANSACTION WHERE T.id_TYPE_TYPE = 1 OR T.id_TYPE_TYPE = 2 ORDER BY T.num_DEPOTouRETRAIT DESC LIMIT 1"



list_sql = [sql1, sql2, sql3, sql4, sql5, sql6, sql7, sql8, sql9, sql10, sql11, sql12, sql13, sql14, sql15, sql16, sql17, sql18, sql19, sql20, sql21, sql22, sql23, sql24, sql25]




